<a href="https://colab.research.google.com/github/azrapatvi/Ml_practice/blob/main/6_support_vector_regressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df=sns.load_dataset('tips')

In [4]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [27]:
df['sex']=df['sex'].map({
    "Female":1,
    "Male":0
})

df['smoker']=df['smoker'].map({
    "Yes":1,
    "No":0
})

df['time']=df['time'].map({
    "Dinner":1,
    "Lunch":0
})

In [28]:
df['time'].value_counts()

time
1    176
0     68
Name: count, dtype: int64

In [29]:
df.head()

   total_bill   tip sex smoker  day time  size
0       16.99  1.01   1      0  Sun    1     2
1       10.34  1.66   0      0  Sun    1     3
2       21.01  3.50   0      0  Sun    1     3
3       23.68  3.31   0      0  Sun    1     2
4       24.59  3.61   1      0  Sun    1     4

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [42]:
df['sex']=df['sex'].astype(int)

In [43]:
df['smoker']=df['smoker'].astype(int)
df['time']=df['time'].astype(int)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    int64
 3   smoker      244 non-null    int64
 4   day         244 non-null    category
 5   time        244 non-null    int64
 6   size        244 non-null    int64
dtypes: category(1), float64(2), int64(4)
memory usage: 12.0 KB

In [45]:
X=df.drop('total_bill',axis=1)
y=df['total_bill']

In [46]:
X

      tip  sex  smoker   day  time  size
0    1.01    1       0   Sun     1     2
1    1.66    0       0   Sun     1     3
2    3.50    0       0   Sun     1     3
3    3.31    0       0   Sun     1     2
4    3.61    1       0   Sun     1     4
..    ...  ...     ...   ...   ...   ...
239  5.92    0       0   Sat     1     3
240  2.00    1       1   Sat     1     2
241  2.00    0       1   Sat     1     2
242  1.75    0       0   Sat     1     2
243  3.00    1       0  Thur     1     2

[244 rows x 6 columns]

In [47]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [48]:
X['day'].dtype

CategoricalDtype(categories=['Thur', 'Fri', 'Sat', 'Sun'], ordered=False, categories_dtype=object)

In [49]:
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    1       0  Sun     1     2
1       10.34  1.66    0       0  Sun     1     3
2       21.01  3.50    0       0  Sun     1     3
3       23.68  3.31    0       0  Sun     1     2
4       24.59  3.61    1       0  Sun     1     4

In [54]:
cat_cols=[i for i in df.columns if df[i].dtypes=='category']

cat_cols

['day']

In [56]:
num_cols=[i for i in X.columns if X[i].dtypes!='category']

num_cols

['tip', 'sex', 'smoker', 'time', 'size']

In [62]:
from sklearn.svm import SVR

svr=SVR(kernel='rbf')

In [59]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer

preprocessor=ColumnTransformer(
    [
        ("num_cols",StandardScaler(),num_cols),
        ("cat_cols",OneHotEncoder(),cat_cols)

    ]
)

In [60]:
preprocessor

ColumnTransformer(transformers=[('num_cols', StandardScaler(),
                                 ['tip', 'sex', 'smoker', 'time', 'size']),
                                ('cat_cols', OneHotEncoder(), ['day'])])

In [63]:
svr

SVR()

In [64]:
from sklearn.pipeline import Pipeline

model=Pipeline(
    [
        ("preprocessor",preprocessor),
        ("model",svr)
    ]
)

In [65]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_cols', StandardScaler(),
                                                  ['tip', 'sex', 'smoker',
                                                   'time', 'size']),
                                                 ('cat_cols', OneHotEncoder(),
                                                  ['day'])])),
                ('model', SVR())])

In [66]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num_cols', StandardScaler(),
                                                  ['tip', 'sex', 'smoker',
                                                   'time', 'size']),
                                                 ('cat_cols', OneHotEncoder(),
                                                  ['day'])])),
                ('model', SVR())])

In [67]:
y_pred=model.predict(X_test)

In [68]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MSE :", mse)
print("RMSE:", rmse)
print("MAE :", mae)
print("R2  :", r2)

MSE : 50.83218463779734
RMSE: 7.129669321770635
MAE : 4.978600781139095
R2  : 0.40048286860836546

In [53]:
df.head(2)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    1       0  Sun     1     2
1       10.34  1.66    0       0  Sun     1     3