<a href="https://colab.research.google.com/github/azrapatvi/Ml_practice/blob/main/8_GaussianNB_on_tips_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
df=sns.load_dataset('tips')

In [10]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [11]:
df['sex']=df['sex'].map({
    "Female":1,
    "Male":0
})

df['smoker']=df['smoker'].map({
    "Yes":1,
    "No":0
})

In [12]:
df

     total_bill   tip sex smoker   day    time  size
0         16.99  1.01   1      0   Sun  Dinner     2
1         10.34  1.66   0      0   Sun  Dinner     3
2         21.01  3.50   0      0   Sun  Dinner     3
3         23.68  3.31   0      0   Sun  Dinner     2
4         24.59  3.61   1      0   Sun  Dinner     4
..          ...   ...  ..    ...   ...     ...   ...
239       29.03  5.92   0      0   Sat  Dinner     3
240       27.18  2.00   1      1   Sat  Dinner     2
241       22.67  2.00   0      1   Sat  Dinner     2
242       17.82  1.75   0      0   Sat  Dinner     2
243       18.78  3.00   1      0  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [14]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [15]:
df['time']=df['time'].map({
    "Dinner":1,
    "Lunch":0
})

In [16]:
df

     total_bill   tip sex smoker   day time  size
0         16.99  1.01   1      0   Sun    1     2
1         10.34  1.66   0      0   Sun    1     3
2         21.01  3.50   0      0   Sun    1     3
3         23.68  3.31   0      0   Sun    1     2
4         24.59  3.61   1      0   Sun    1     4
..          ...   ...  ..    ...   ...  ...   ...
239       29.03  5.92   0      0   Sat    1     3
240       27.18  2.00   1      1   Sat    1     2
241       22.67  2.00   0      1   Sat    1     2
242       17.82  1.75   0      0   Sat    1     2
243       18.78  3.00   1      0  Thur    1     2

[244 rows x 7 columns]

In [17]:
X=df.drop('time',axis=1)
y=df['time']

In [18]:
X

     total_bill   tip sex smoker   day  size
0         16.99  1.01   1      0   Sun     2
1         10.34  1.66   0      0   Sun     3
2         21.01  3.50   0      0   Sun     3
3         23.68  3.31   0      0   Sun     2
4         24.59  3.61   1      0   Sun     4
..          ...   ...  ..    ...   ...   ...
239       29.03  5.92   0      0   Sat     3
240       27.18  2.00   1      1   Sat     2
241       22.67  2.00   0      1   Sat     2
242       17.82  1.75   0      0   Sat     2
243       18.78  3.00   1      0  Thur     2

[244 rows x 6 columns]

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(handle_unknown='ignore')
cat_cols=['day']
num_cols=['total_bill','tip','sex','smoker','size']

preprocessor=ColumnTransformer(
  [
      ("cat_cols",ohe,cat_cols),
      ("num_cols","passthrough",num_cols)
  ]
)

In [27]:
preprocessor

ColumnTransformer(transformers=[('cat_cols',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['day']),
                                ('num_cols', 'passthrough',
                                 ['total_bill', 'tip', 'sex', 'smoker',
                                  'size'])])

In [28]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
from sklearn.naive_bayes import GaussianNB

model=GaussianNB()

In [30]:
from sklearn.pipeline import Pipeline

pipeline=Pipeline(
    [
        ("preprocessor",preprocessor),
        ("model",model)
    ]
)

In [31]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat_cols',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['day']),
                                                 ('num_cols', 'passthrough',
                                                  ['total_bill', 'tip', 'sex',
                                                   'smoker', 'size'])])),
                ('model', GaussianNB())])

In [36]:
y_pred=pipeline.predict(X_test)

In [37]:
y_pred

array([1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0])

In [38]:
X

     total_bill   tip sex smoker   day  size
0         16.99  1.01   1      0   Sun     2
1         10.34  1.66   0      0   Sun     3
2         21.01  3.50   0      0   Sun     3
3         23.68  3.31   0      0   Sun     2
4         24.59  3.61   1      0   Sun     4
..          ...   ...  ..    ...   ...   ...
239       29.03  5.92   0      0   Sat     3
240       27.18  2.00   1      1   Sat     2
241       22.67  2.00   0      1   Sat     2
242       17.82  1.75   0      0   Sat     2
243       18.78  3.00   1      0  Thur     2

[244 rows x 6 columns]

In [39]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9591836734693877
[[15  0]
 [ 2 32]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94        15
           1       1.00      0.94      0.97        34

    accuracy                           0.96        49
   macro avg       0.94      0.97      0.95        49
weighted avg       0.96      0.96      0.96        49

In [40]:
new_data = pd.DataFrame({
    'total_bill': [20.50],
    'tip': [3.50],
    'sex': [0],       # 0 = Male
    'smoker': [0],    # 0 = No
    'day': ['Sun'],
    'size': [3]
})

prediction = pipeline.predict(new_data)

print(prediction)

[1]